export const ADD_LISTTO_CART = "ADD_LISTTO_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const TOTAL_PRICES = "TOTAL_PRICES";
export const INCREATE_QUANTITY_CART = "INCREATE_QUANTITY_CART";
export const DECREASE_QUANTITY_CART = "DECREASE_QUANTITY_CART";
export const ADD_TO_CART_WITH_MULTIPLE_QUANTITY = "ADD_TO_CART_WITH_MULTIPLE_QUANTITY";
export const ADD_PROMOTION_VALUES = "ADD_PROMOTION_VALUES";
export const CALCULATETOTAL = "CALCULATETOTAL";
//product
export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_IMAGE_TO_PRODUCT = "ADD_IMAGE_TO_PRODUCT"

