// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using SWPSolution.Data.Entities;

namespace SWPSolution.Data.Entities
{
    public partial class SWPSolutionDBContext
    {

        [DbFunction("generate_blog_id", "dbo")]
        public static string generate_blog_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_categories_id", "dbo")]
        public static string generate_categories_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_order_id", "dbo")]
        public static string generate_order_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_payment_id", "dbo")]
        public static string generate_payment_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_preorder_id", "dbo")]
        public static string generate_preorder_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_product_id", "dbo")]
        public static string generate_product_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_review_id", "dbo")]
        public static string generate_review_id()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("generate_staff_id", "dbo")]
        public static string generate_staff_id(string role)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
