// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class Address
{
    public string AddressId { get; set; }

    public string MemberId { get; set; }

    public string HouseNumber { get; set; }

    public string Street { get; set; }

    public string District { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public virtual Member Member { get; set; }
}