// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class AppRole : IdentityRole<Guid>
{
    public string Description { get; set; }
}