// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public class AppUser : IdentityUser<Guid>
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string TemporaryPassword { get; set; }
    public string EmailVerificationCode { get; set; }
    public DateTime? EmailVerificationExpiry { get; set; }
}