// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class Blog
{
    public string BlogId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Categories { get; set; }

    public DateTime? DataCreate { get; set; }

    public string StaffId { get; set; }

    public virtual Staff Staff { get; set; }
}