// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class Category
{
    public string CategoriesId { get; set; }

    public string BrandName { get; set; }

    public string AgeRange { get; set; }

    public string SubCategories { get; set; }

    public string PackageType { get; set; }

    public string Source { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}