// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SWPSolution.Data.Entities;

public partial class OrderDetail
{
    [Required]
    public string OrderDetailId { get; set; }

    [Required]
    public string OrderId { get; set; }

    [Required]
    public string ProductId { get; set; }

    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1.")]

    public int Quantity { get; set; }

    public float Price { get; set; }

    

    public virtual Product Product { get; set; }
    [JsonIgnore]
    public virtual Order Order { get; set; }
}