// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class PreOrder
{
    public string PreorderId { get; set; }

    public string ProductId { get; set; }

    public string MemberId { get; set; }

    public int? Quantity { get; set; }

    public DateTime? PreorderDate { get; set; }

    public double? Price { get; set; }

    public virtual Member Member { get; set; }

    public virtual Product Product { get; set; }
}