// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class ProductImage
{
    public int Id { get; set; }

    public string ProductId { get; set; }

    public string ImagePath { get; set; }

    public string Caption { get; set; }

    public DateTime DateCreated { get; set; }

    public int SortOrder { get; set; }

    public long FileSize { get; set; }

    public virtual Product Product { get; set; }
}